### ISSUE TITLE
Error importing CSDL

### ISSUE THREAD

**Issue by darshansarojini** [LSDOlab/csdl#3]
>>> import csdl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/darshan/Documents/GitHub/LSDO/csdl/csdl/__init__.py", line 1, in <module>
    from csdl.core.model import Model
  File "/home/darshan/Documents/GitHub/LSDO/csdl/csdl/core/model.py", line 11, in <module>
    from csdl.core.bracketed_search_operation import BracketedSearchOperation
  File "/home/darshan/Documents/GitHub/LSDO/csdl/csdl/core/bracketed_search_operation.py", line 10, in <module>
    class BracketedSearchOperation(Operation):
  File "/home/darshan/Documents/GitHub/LSDO/csdl/csdl/core/bracketed_search_operation.py", line 21, in BracketedSearchOperation
    brackets: Dict[str, Tuple[np.ndarray | Variable,
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by darshansarojini** [comment]
I tried a fresh installation of CSDL on my desktop, and ran into this issue.
OS: Ubuntu 20.04
